from __future__ import annotations


CLASS_ID_TO_NAME = {
    1: "Warrior",
    2: "Paladin",
    3: "Hunter",
    4: "Rogue",
    5: "Priest",
    6: "Death Knight",
    7: "Shaman",
    8: "Mage",
    9: "Warlock",
    10: "Monk",
    11: "Druid",
    12: "Demon Hunter",
    13: "Evoker",
}

SPEC_ID_TO_INFO = {
    62: ("Mage", "Arcane"),
    63: ("Mage", "Fire"),
    64: ("Mage", "Frost"),
    65: ("Paladin", "Holy"),
    66: ("Paladin", "Protection"),
    70: ("Paladin", "Retribution"),
    71: ("Warrior", "Arms"),
    72: ("Warrior", "Fury"),
    73: ("Warrior", "Protection"),
    102: ("Druid", "Balance"),
    103: ("Druid", "Feral"),
    104: ("Druid", "Guardian"),
    105: ("Druid", "Restoration"),
    250: ("Death Knight", "Blood"),
    251: ("Death Knight", "Frost"),
    252: ("Death Knight", "Unholy"),
    253: ("Hunter", "Beast Mastery"),
    254: ("Hunter", "Marksmanship"),
    255: ("Hunter", "Survival"),
    256: ("Priest", "Discipline"),
    257: ("Priest", "Holy"),
    258: ("Priest", "Shadow"),
    259: ("Rogue", "Assassination"),
    260: ("Rogue", "Outlaw"),
    261: ("Rogue", "Subtlety"),
    262: ("Shaman", "Elemental"),
    263: ("Shaman", "Enhancement"),
    264: ("Shaman", "Restoration"),
    265: ("Warlock", "Affliction"),
    266: ("Warlock", "Demonology"),
    267: ("Warlock", "Destruction"),
    268: ("Monk", "Brewmaster"),
    269: ("Monk", "Windwalker"),
    270: ("Monk", "Mistweaver"),
    577: ("Demon Hunter", "Havoc"),
    581: ("Demon Hunter", "Vengeance"),
    1467: ("Evoker", "Devastation"),
    1468: ("Evoker", "Preservation"),
    1473: ("Evoker", "Augmentation"),
    1480: ("Demon Hunter", "Devourer"),
}

CLASS_SLUG_TO_NAME = {
    "deathknight": "Death Knight",
    "demonhunter": "Demon Hunter",
    "druid": "Druid",
    "evoker": "Evoker",
    "hunter": "Hunter",
    "mage": "Mage",
    "monk": "Monk",
    "paladin": "Paladin",
    "priest": "Priest",
    "rogue": "Rogue",
    "shaman": "Shaman",
    "warlock": "Warlock",
    "warrior": "Warrior",
}

SPEC_SLUG_TO_NAME = {
    "arcane": "Arcane",
    "arms": "Arms",
    "assassination": "Assassination",
    "augmentation": "Augmentation",
    "balance": "Balance",
    "beastmastery": "Beast Mastery",
    "blood": "Blood",
    "brewmaster": "Brewmaster",
    "demonology": "Demonology",
    "destruction": "Destruction",
    "devastation": "Devastation",
    "devourer": "Devourer",
    "discipline": "Discipline",
    "elemental": "Elemental",
    "enhancement": "Enhancement",
    "feral": "Feral",
    "fire": "Fire",
    "frost": "Frost",
    "fury": "Fury",
    "guardian": "Guardian",
    "havoc": "Havoc",
    "holy": "Holy",
    "marksmanship": "Marksmanship",
    "mistweaver": "Mistweaver",
    "outlaw": "Outlaw",
    "preservation": "Preservation",
    "protection": "Protection",
    "restoration": "Restoration",
    "retribution": "Retribution",
    "shadow": "Shadow",
    "subtlety": "Subtlety",
    "survival": "Survival",
    "unholy": "Unholy",
    "vengeance": "Vengeance",
    "windwalker": "Windwalker",
}
